# å¼€å‘ç¯å¢ƒé…ç½®
server:
  prefix: '/api'
  port: 5002
  collaborationPort: 5003
  maxDocumentVersion: 20 # æœ€å¤§ç‰ˆæœ¬è®°å½•æ•°
  logRetainDays: 3 # æ—¥å¿—ä¿ç•™å¤©æ•°ï¼Œæ¯”å¦‚åªä¿ç•™è¿‘ä¸‰å¤©æ—¥å¿—
  enableRateLimit: true # æ˜¯å¦é™æµ
  rateLimitWindowMs: 60000 # é™æµæ—¶é—´
  rateLimitMax: 1000 # å•ä½é™æµæ—¶é—´å†…å•ä¸ª ip æœ€å¤§è®¿é—®æ•°é‡
  email: # é‚®ç®±æœåŠ¡ï¼Œå‚è€ƒ http://help.163.com/09/1223/14/5R7P6CJ600753VB8.html?servCode=6010376 è·å– SMTP é…ç½®
    host: ''
    port: 465
    user: ''
    password: ''
  admin:
    name: 'admin' # æ³¨æ„ä¿®æ”¹
    password: 'admin' # æ³¨æ„ä¿®æ”¹
    email: 'admin@foxmail.com' # æ³¨æ„ä¿®æ”¹ä¸ºçœŸå®é‚®ç®±åœ°å€

# æ•°æ®åº“é…ç½®
db:
  mysql:
    host: 'localhost'
    username: 'root'
    password: 'root'
    database: 'root'
    port: 3306
    charset: 'utf8mb4'
    timezone: '+08:00'
    synchronize: true
  redis:
    host: 'localhost'
    port: '6379'
    username: 'default'
    password: '123456'

# oss æ–‡ä»¶å­˜å‚¨æœåŠ¡
oss:
  local:
    enable: true
    # çº¿ä¸Šæ›´æ”¹ä¸ºæœåŠ¡ç«¯åœ°å€ï¼ˆå¦‚ï¼šhttps://api.codingit.cnï¼‰
    server: 'http://localhost:5002'
  # ä»¥ä¸‹ä¸ºå„å‚å•† sdk é…ç½®ï¼Œä¸è¦ä¿®æ”¹å­—æ®µï¼Œå¡«å…¥å€¼å³å¯
  tencent:
    enable: false
    config:
      SecretId: ''
      SecretKey: ''
      Bucket: ''
      Region: ''
  aliyun:
    enable: false
    config:
      accessKeyId: ''
      accessKeySecret: ''
      bucket: ''
      https: true
      region: ''

# jwt é…ç½®
jwt:
  secretKey: 'zA_Think+KNOWLEDGE+WIKI+DOCUMENTS@2022'
  expiresIn: '6h'

# weixin é…ç½®
wx:
  appId: ''
  authUrl: ''
  secret: ''
  grantType: ''

# swagger é…ç½®
swagger:
  setupHttp: 'http://127.0.0.1'
  setupPath: 'api-docs' # swagger Apiæ–‡æ¡£è®¿é—®è·¯å¾„
  title: 'SlayKit Server' # æ ‡é¢˜
  titleDesc: 'ğŸš€ SlayKit Server DEV API' # æè¿°
  apiVersion: '1.0' # APIç‰ˆæœ¬
  prefix: '/api' # Swagger Api Prefix
  cdnUrl: 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.7.2' # Swagger CDN Url

